# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- pos_bank_statement_line_no_change
- pos_payment_change
repo_description: This project aims to deal with Odoo modules related to the Point
    of Sale.
repo_name: Point of Sale
repo_slug: pos
repo_website: https://github.com/OCA/pos
travis_apt_packages: []
travis_apt_sources: []

