# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.2.2
_src_path: https://github.com/grap/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
rebel_module_groups: []
repo_description: Point Of Sale Repository Description
repo_name: Point of Sale
repo_slug: pos
travis_apt_packages: []
travis_apt_sources: []

