from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


class PosPaymentMethodFee(models.Model):
    _name = "pos.payment.method.fee"
    _description = "POS Payment Method Fee Rule"
    _order = "sequence, id"

    name = fields.Char(required=True)

    payment_method_id = fields.Many2one(
        comodel_name="pos.payment.method",
        string="Payment Method",
        required=True,
        ondelete="cascade",
        index=True,
    )

    fee_type = fields.Selection(
        selection=[
            ("percentage", "Percentage"),
            ("fixed", "Fixed"),
        ],
        required=True,
        default="percentage",
    )

    amount = fields.Float(
        required=True,
        digits="Product Price",
        help="Percentage value (e.g. 1.5 for 1.5%%) when Fee Type is "
        "'Percentage', or the fixed amount charged per transaction "
        "when Fee Type is 'Fixed'.",
    )

    account_id = fields.Many2one(
        comodel_name="account.account",
        string="Fee Account",
        required=True,
        help="Expense account used to book this financial cost.",
    )

    counterpart_account_id = fields.Many2one(
        comodel_name="account.account",
        string="Counterpart Account",
        required=True,
        help="Account credited (or debited on refunds) as counterpart of "
        "the fee expense, typically the outstanding/bank account of "
        "the payment method.",
    )

    journal_id = fields.Many2one(
        comodel_name="account.journal",
        string="Posting Journal",
        required=True,
        help="Accounting journal used to post the journal entries "
        "generated by this fee rule.",
    )

    posting_policy = fields.Selection(
        selection=[
            ("immediate", "Immediate"),
            ("session_close", "At Session Close"),
        ],
        required=True,
        default="session_close",
        help="Immediate: the accounting entry is generated right after "
        "the payment is registered.\n"
        "At Session Close: the fee is calculated immediately but the "
        "accounting entry is generated (and optionally grouped) when "
        "the POS session is closed.",
    )

    company_id = fields.Many2one(
        comodel_name="res.company",
        string="Company",
        required=True,
        default=lambda self: self.env.company,
    )

    sequence = fields.Integer(default=10)

    active = fields.Boolean(default=True)

    @api.constrains("fee_type", "amount")
    def _check_amount(self):
        for rule in self:
            if rule.fee_type == "percentage" and not (0 <= rule.amount <= 100):
                raise ValidationError(
                    _('The percentage fee "%(name)s" must be between 0 and 100.')
                    % {"name": rule.name}
                )
            if rule.fee_type == "fixed" and rule.amount < 0:
                raise ValidationError(
                    _('The fixed fee "%(name)s" must be a positive amount.')
                    % {"name": rule.name}
                )

    def _compute_fee_amount(self, amount_base):
        """Calculate the fee amount for a given transaction base amount.

        A negative ``amount_base`` (refund) yields a negative fee amount so
        that the financial cost is reversed symmetrically.
        """
        self.ensure_one()
        if self.fee_type == "percentage":
            return amount_base * (self.amount / 100.0)
        if self.fee_type == "fixed":
            sign = 1.0 if amount_base >= 0 else -1.0
            return sign * abs(self.amount)
        return 0.0
