{
    "name": "Disable Pricelist selection button in POS",
    "version": "14.0.1.0.1",
    "summary": "Disable Pricelist selection button in POS",
    "author": "Ooops, Cetmix, Odoo Community Association (OCA)",
    "contributors": "Cetmix",
    "license": "LGPL-3",
    "category": "Purchase",
    "website": "https://github.com/OCA/pos",
    "depends": ["point_of_sale"],
    "external_dependencies": {},
    "demo": [],
    "data": ["views/assets.xml", "views/pos_config_view.xml"],
    "qweb": ["static/src/xml/ClientDetailsEdit.xml"],
    "installable": True,
    "application": False,
}
