# SPDX-FileCopyrightText: 2025 Coop IT Easy SC
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from odoo import models


class DonationLine(models.Model):
    _inherit = "donation.line"

    def _compute_in_kind(self):
        """Donation in PoS should be considered as donation in-kind.
        These donation should not generate account move,
        because account move has already been generated by the PoS.
        """
        res = super()._compute_in_kind()
        for line in self:
            # If line is not already considered a an in-kind donation,
            # then we must check if it’s a pos_donation
            if not line.in_kind:
                line.in_kind = line.product_id.detailed_type == "donation_in_pos"
        return res
