[project]
name = "odoo-addons-oca-pos"
version = "19.0.20260825.0"
dependencies = [
    "odoo-addon-pos_edit_order_line==19.0.*",
    "odoo-addon-pos_partner_birthdate==19.0.*",
    "odoo-addon-pos_printing_qztray==19.0.*",
    "odoo-addon-pos_session_sequence==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
