[project]
name = "odoo-addons-oca-pos"
version = "18.0.20260825.0"
dependencies = [
    "odoo-addon-pos_barcode_rule_priced_with_change_rate==18.0.*",
    "odoo-addon-pos_blind_session_closing==18.0.*",
    "odoo-addon-pos_cash_control_extension==18.0.*",
    "odoo-addon-pos_config_logo==18.0.*",
    "odoo-addon-pos_customer_tree_view_vat==18.0.*",
    "odoo-addon-pos_display_order_number==18.0.*",
    "odoo-addon-pos_display_total_quantity==18.0.*",
    "odoo-addon-pos_divide_order_summary==18.0.*",
    "odoo-addon-pos_lot_barcode==18.0.*",
    "odoo-addon-pos_margin==18.0.*",
    "odoo-addon-pos_order_remove_line==18.0.*",
    "odoo-addon-pos_order_to_sale_order==18.0.*",
    "odoo-addon-pos_partner_birthdate==18.0.*",
    "odoo-addon-pos_payment_method_cashdro==18.0.*",
    "odoo-addon-pos_payment_terminal==18.0.*",
    "odoo-addon-pos_product_display_default_code==18.0.*",
    "odoo-addon-pos_product_expiry==18.0.*",
    "odoo-addon-pos_product_multi_barcode==18.0.*",
    "odoo-addon-pos_report_session_summary==18.0.*",
    "odoo-addon-pos_sale_picking_keep==18.0.*",
    "odoo-addon-pos_session_pay_invoice==18.0.*",
    "odoo-addon-pos_session_sequence==18.0.*",
    "odoo-addon-pos_supplierinfo_search==18.0.*",
    "odoo-addon-pos_user_restrict_provider_info==18.0.*",
    "odoo-addon-pos_user_restriction==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
