import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo12-addons-oca-pos",
    description="Meta package for oca-pos Odoo addons",
    version=version,
    install_requires=[
        'odoo12-addon-pos_accented_search',
        'odoo12-addon-pos_access_right',
        'odoo12-addon-pos_cash_move_reason',
        'odoo12-addon-pos_customer_display',
        'odoo12-addon-pos_customer_required',
        'odoo12-addon-pos_default_empty_image',
        'odoo12-addon-pos_default_partner',
        'odoo12-addon-pos_empty_home',
        'odoo12-addon-pos_fix_search_limit',
        'odoo12-addon-pos_fixed_discount',
        'odoo12-addon-pos_invoice_send_mail',
        'odoo12-addon-pos_invoicing',
        'odoo12-addon-pos_journal_image',
        'odoo12-addon-pos_margin',
        'odoo12-addon-pos_multi_ean',
        'odoo12-addon-pos_order_mgmt',
        'odoo12-addon-pos_order_remove_line',
        'odoo12-addon-pos_order_return',
        'odoo12-addon-pos_order_return_traceability',
        'odoo12-addon-pos_order_to_sale_order',
        'odoo12-addon-pos_partner_firstname',
        'odoo12-addon-pos_payment_change',
        'odoo12-addon-pos_payment_terminal',
        'odoo12-addon-pos_picking_delayed',
        'odoo12-addon-pos_picking_load',
        'odoo12-addon-pos_picking_load_partner_name',
        'odoo12-addon-pos_place',
        'odoo12-addon-pos_price_to_weight',
        'odoo12-addon-pos_quick_logout',
        'odoo12-addon-pos_report_session_summary',
        'odoo12-addon-pos_require_product_quantity',
        'odoo12-addon-pos_reset_search',
        'odoo12-addon-pos_session_closing_stock_error',
        'odoo12-addon-pos_session_pay_invoice',
        'odoo12-addon-pos_supplierinfo_barcode',
        'odoo12-addon-pos_supplierinfo_search',
        'odoo12-addon-pos_tare',
        'odoo12-addon-pos_ticket_logo',
        'odoo12-addon-pos_ticket_salesman_firstname',
        'odoo12-addon-pos_ticket_without_price',
        'odoo12-addon-pos_to_weight_by_product_uom',
        'odoo12-addon-pos_user_restriction',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
    ]
)
